### ISSUE TITLE
Wrong meta description created by page overwrite

### ISSUE THREAD

**Issue by revlis-x** [DivanteLtd/vue-storefront#3091]
## Current behavior
Core Pages that overwrite the default meta desc from head.js output wrong attributes, e.g.

https://github.com/DivanteLtd/vue-storefront/blob/e14a2a0abde6f71a48e21c8e694b5502e50d3aa3/core/pages/Category.js#L296

## Expected behavior
Instead we need something like:
```
{ vmid: 'description', name: 'description', content: htmlDecode(this.category.meta_description) }
```

## Can you handle fixing this bug by yourself?

- [X] YES, but not right now
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [x] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [ ] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.
