### ISSUE TITLE
duplicate vue-meta render

### ISSUE THREAD

**Issue by gibkigonzo** [DivanteLtd/vue-storefront#4203]
## Current behavior

After upgrading vue-meta there are some breaking changes that makes duplicate render. There are duplicate scripts and other elements in head, for example `lang="en en"`

## Expected behavior

There are no duplications.

## Steps to reproduce the issue

1. load vsf in dev mode on master branch

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [x] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version: 

## Additional information

https://vue-meta.nuxtjs.org/guide/caveats.html#duplicated-tags-after-hydration-with-ssr
https://github.com/nuxt/vue-meta/issues/391
