### ISSUE TITLE
Apply new SSR engine from Nuxt.js

### ISSUE THREAD

**Issue by andrzejewsky** [DivanteLtd/vue-storefront#4667]
As the Nuxt.js team has introduced [compositon API](https://composition-api.now.sh) that supports SSR, we want to use that solution instead our own SSR implementation. There are following steps that need to be done:

- [x] Update composition API to `^0.6.7` and install https://composition-api.now.sh (https://github.com/DivanteLtd/vue-storefront/issues/4668)
- [x] Replace SSR for useCategoryFactory and update tests (https://github.com/DivanteLtd/vue-storefront/issues/4669)
- [x] Replace SSR for useProductFactory and update tests (https://github.com/DivanteLtd/vue-storefront/issues/4670)
- [ ] Replace SSR for useCartFactory and update tests (https://github.com/DivanteLtd/vue-storefront/issues/4671)
- [ ] Replace SSR for useUserFactory and update tests (https://github.com/DivanteLtd/vue-storefront/issues/4672)
- [ ] Replace SSR for useUserOrdersFactory and update tests (https://github.com/DivanteLtd/vue-storefront/issues/4673)
- [ ] Replace SSR for useWhishlistFactory and update tests (https://github.com/DivanteLtd/vue-storefront/issues/4674)
- [ ] Replace SSR for useLocale (commercetools) and update tests (https://github.com/DivanteLtd/vue-storefront/issues/4675)
- [ ] Replace SSR everywhere else that references to old ssr solution
