### ISSUE TITLE
Make posibility to extend webpack build in themes

### ISSUE THREAD

**Issue by filrak** [DivanteLtd/vue-storefront#707]
There should be posibility to extend the webpack build (at least `webpack.base` for now) from themes since core build will be untouchable.

I recommend using this for merging
https://github.com/survivejs/webpack-merge

We should have posibility to add `webpack.extend.js` file in `theme/themename/` which will be merged with current build.

- [ ] Add posibility to merge `webpack.extend.js`  with `webpack.base.config.js` from theme if the file exists
- [ ] Make sure the extended config works properly
- [ ] Describe the solution in docs [link](https://github.com/DivanteLtd/vue-storefront/blob/master/doc/Working%20with%20webpack.md)

**Comment by pkarw** [comment]
This is very important, agree.

**Comment by marlass** [comment]
I can take on that one.

**Comment by filrak** [comment]
@marlass if you want to do more you can make posibility to extend all builds (make `build-extend` folder in  themes and add 3 webpack files named the same as build)

**Comment by pkarw** [comment]
Can we close this on @filrak?
